### ISSUE TITLE
希望能添加名片赞，以及在发送消息5000ms的时候提供一个错误日志，以及推送一个发送消息失败的事件

### ISSUE THREAD

**Issue by kukume** [IceCream-QAQ/Rain#45]
希望能添加名片赞，以及在发送消息5000ms的时候提供一个错误日志，以及推送一个发送消息失败的日志

**Comment by IceCream-QAQ** [comment]
问题移交至：
YuQWorks/YuQ#62
YuQWorks/YuQ-ArtQQ#3
YuQWorks/YuQ-ArtQQ#4
