### ISSUE TITLE
RainCode错误

### ISSUE THREAD

**Issue by kukume** [IceCream-QAQ/Rain#48]
发送图片之后，把Message转成RainCode，图片转换异常 
![)O0DK5X$ }I} F~1B@U8){T](https://user-images.githubusercontent.com/45278810/155046462-b1233bf6-f1c3-4278-b4fa-6c92649ffb24.png)

**Comment by IceCream-QAQ** [comment]
问题已经移交至 YuQWorks/YuQ-ArtQQ#2
